config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
                  url(r'^i18n/', include('django.conf.urls.i18n')),

                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='home'),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^bills/', include('wild_bills.bills.urls', namespace='bills')),
    url(r'^categories/', include('wild_bills.categories.urls', namespace='categories')),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}


    # User management
    url(r'^users/', include('wild_bills.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

wild_bills/bills/urls.py
from django.conf.urls import url

from wild_bills.bills.views import DebtCreateView, DebtDetailView, DebtUpdateView, DebtListView, BillCreateView, BillListView, \
    BillDetailView, BillUpdateView, DebtDeleteView, \
    PaymentCreateView


urlpatterns = [
    #url(r'^profile/create/$', WildBillsProfileCreateView.as_view(), name='profile-create'),
    #url(r'^profile/(?P<pk>[\d]*)/update$', WildBillsProfileUpdateView.as_view(), name='profile-update'),
    url(r'^debt/$', DebtListView.as_view(), name='debt-list'),
    url(r'^debt/create/$', DebtCreateView.as_view(), name='debt-create'),
    url(r'^debt/(?P<pk>[\d]*)/$', DebtDetailView.as_view(), name='debt-detail'),
    url(r'^debt/(?P<pk>[\d]*)/update$', DebtUpdateView.as_view(), name='debt-update'),
    url(r'^debt/(?P<pk>[\d]*)/delete$', DebtDeleteView.as_view(), name='debt-delete'),
    url(r'^bill/$', BillListView.as_view(), name='bill-list'),
    url(r'^bill/paid/$', BillListView.as_view(), kwargs={'status': 'PAID'}, name='bill-list-paid'),
    url(r'^bill/create/$', BillCreateView.as_view(), name='bill-create'),
    url(r'^bill/(?P<pk>[\d]*)/$', BillDetailView.as_view(), name='bill-detail'),
    url(r'^bill/(?P<pk>[\d]*)/update$', BillUpdateView.as_view(), name='bill-update'),
    url(r'^payment/create/(?P<bill_pk>[\d]*)/$', PaymentCreateView.as_view(), name='payment-create'),
]

wild_bills/categories/urls.py
from django.conf.urls import url

from .views import CategoryListView, CategoryDetailView

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name='category-list'),
    # url(r'^/create/$', CategoryCreateView.as_view(), name='category-create'),
    url(r'^(?P<slug>[\w-]*)/$', CategoryDetailView.as_view(), name='category-detail'),
    # url(r'^/(?P<pk>[\d]*)/update$', CategoryUpdateView.as_view(), name='category-update'),
]

wild_bills/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

wild_bills/bills/models.py
from datetime import date
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from django.utils import timezone
from model_utils.models import TimeStampedModel

from ..categories.models import Category
from .managers import BillManager, DebtManager
from .utils import frequency_calculator
import logging

logger = logging.getLogger(__name__)


# class WildBillsProfile(AbstractUser):
#     country = CountryField(verbose_name= _('Country'))


class Organization(models.Model):
    display_name = models.CharField(_('Display name'), max_length=150,
                                    help_text=_("Name that you communicate"))
    legal_name = models.CharField(_('Legal name'), max_length=150, blank=True,
                                  help_text=_("Official name. Only relevant if the organization is a company"))

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name="owned_organizations",
                              verbose_name=_('Owner'))
    members = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name="organizations",
                                     verbose_name=_('Members') )

    class Meta:
        pass

    def __str__(self):
        return self.display_name


class PaymentFrequency(models.Model):
    FREQ_MONTHLY = 'Monthly'
    FREQ_WEEKLY = 'Weekly'
    FREQ_BIWEEKLY = 'Biweekly'
    FREQ_CHOICES = (
        (FREQ_MONTHLY, _('Monthly')),
        (FREQ_WEEKLY, _('Weekly')),
        (FREQ_BIWEEKLY, _('Biweekly'))
    )
    frequency_values = models.CharField(_('Frequency values'), max_length=60, blank=True,
                                        help_text=_('Which days of the month or days of the week the payment '
                                                    'should occur. Values separated by comma'))
    frequency = models.CharField(_('Frequency'), max_length=15, choices=FREQ_CHOICES, default=FREQ_MONTHLY)
    start_date = models.DateField(_('Start date'), null=True, blank=True)

    def get_days_of_the_month(self):
        day_list = list()
        if self.frequency_values:
            str_days = self.frequency_values.split(',')
            for str_day in str_days:
                day_list.append(int(str_day))
        return sorted(day_list)

    def calculate_next_date(self, ref_date):
        if self.frequency == self.FREQ_MONTHLY:
            days_list = self.get_days_of_the_month()
            next_date = frequency_calculator.get_next_closest(ref_date, days_list)
            return next_date

        else:
            raise NotImplementedError('Only montly frequency is supported')

    def __str__(self):
        if self.frequency == self.FREQ_MONTHLY:
            return _('Pay every month on %s of the month') % self.frequency_values
        elif self.frequency == self.FREQ_WEEKLY:
            return _('Pay every week on %s') % self.frequency_values
        elif self.frequency == self.FREQ_BIWEEKLY:
            return _('Pay every two weeks on %s') % self.frequency_values
        else:
            return _('No frequency has been selected')


class Debt(TimeStampedModel):
    payee = models.CharField(_('Payee'), max_length=150)
    description = models.CharField(_('Description'), max_length=255)
    amount = models.DecimalField(_('Amount'), max_digits=12, decimal_places=2)
    fixed_amount = models.BooleanField(_('Fixed amount'), default=False)
    organization = models.ForeignKey(Organization, related_name='debts',
                                     verbose_name=_('Organization'))
    frequency = models.ForeignKey(PaymentFrequency,
                                  verbose_name=_('Frequency'))
    end_date = models.DateField(_('End date'), null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name=_('Category'),
                                 related_name='debts', null=True, blank=True)

    objects = DebtManager()

    def get_absolute_url(self):
        return reverse('bills:debt-detail', args=[self.pk])

    def create_bills(self, count=2):
        bills_created = list()
        last_bill = Bill.objects.filter(debt=self).order_by('-due_date').first()
        if last_bill:
            start_date = last_bill.due_date
        else:
            start_date = timezone.now().date()
        for c in range(1,count+1):
            if self.frequency.frequency == self.frequency.FREQ_MONTHLY:
                due_date = self.frequency.calculate_next_date(start_date)
                logger.debug('Adding %d bill for %s' % (c, due_date.strftime('%Y-%m-%d')))
                new_bill = Bill.objects.create(debt=self, amount=self.amount, due_date=due_date)
                bills_created.append(new_bill)
                start_date = due_date
            else:
                raise NotImplementedError('Only monthly frequency is supported to create bills')
        return bills_created


class Payment(models.Model):

    amount = models.DecimalField(_('Amount'),
                                 decimal_places=2,
                                 max_digits=12)
    detail = models.CharField(_('Detail'), max_length=255,
                              blank=True,
                              null=True)
    date_paid = models.DateField(_('Date paid'), default=date.today)
    reference = models.CharField(_('Reference'), max_length=255,
                                 blank=True,
                                 null=True)


    class Meta:
        ordering = ('-date_paid',)

    def __str__(self):
        if self.detail:
            return self.detail
        return _("Payment of {}").format(self.amount)


class Bill(TimeStampedModel):
    STATUS_UNPAID = 'UNPAID'
    STATUS_PAID = 'PAID'
    STATUS_UNDER_PAID = 'UNDER_PAID'
    STATUS_OVER_PAID = 'OVER_PAID'
    STATUS_CHOICES = (
        (STATUS_UNPAID, _('Unpaid')),
        (STATUS_PAID, _('Paid')),
        (STATUS_UNDER_PAID, _('Under paid')),
        (STATUS_OVER_PAID, _('Over paid'))
    )
    debt = models.ForeignKey(Debt, related_name='debts', verbose_name=_('Debt'))
    amount = models.DecimalField(_('Amount'),
                                 decimal_places=2,
                                 max_digits=12)
    due_date = models.DateField(_('Due date'))
    payments = models.ManyToManyField(Payment, related_name='bills', verbose_name=_('Payments'))
    status = models.CharField(_('Status'), max_length=10, choices=STATUS_CHOICES, default=STATUS_UNPAID)
    objects = BillManager()

    def amount_paid(self):
        total_paid = Payment.objects.filter(bills=self).aggregate(Sum('amount'))
        return total_paid['amount__sum']

    def set_status(self):
        total_paid = self.amount_paid()
        if total_paid == self.amount:
            self.status = self.STATUS_PAID
        elif total_paid > self.amount:
            self.status = self.STATUS_OVER_PAID
        elif total_paid < self.amount and self.amount != 0:
            self.status = self.STATUS_UNDER_PAID
        else:
            self.status = self.STATUS_UNPAID

    def pay(self, amount=0.0, date_paid=timezone.now().date()):
        if amount == 0.0:
            amount = self.amount
        payment_sum = Payment.objects.filter(bills=self).aggregate(Sum('amount'))
        if payment_sum['amount__sum']is None or payment_sum['amount__sum'] < self.amount:
            payment = Payment.objects.create(amount=amount, date_paid=date_paid)
            self.payments.add(payment)
            self.set_status()
            self.save()
            return payment
        elif payment_sum['amount__sum'] >= self.amount:
            return None

    def amount_due(self):
        payment_sum = Payment.objects.filter(bills=self).aggregate(Sum('amount'))
        if payment_sum['amount__sum']is None:
            return self.amount
        else:
            return  Decimal(self.amount) -payment_sum['amount__sum']

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     super(Bill, self).save(force_insert=force_insert, force_update=force_update,
    #                                   using=using, update_fields=update_fields)
    #     self.set_status()
    #     return super(Bill, self).save(force_insert=force_insert, force_update=force_update,
    #                                   using=using, update_fields=update_fields)

    class Meta:
        unique_together = ('debt', 'due_date')

wild_bills/categories/forms.py
from django import forms
from parler.forms import TranslatableModelForm

from .models import Category


class CategoryForm(TranslatableModelForm):

    class Meta:
        model = Category
        fields = ['name', 'is_public', ]

wild_bills/categories/views.py
from braces.views import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.views.generic import UpdateView, CreateView, DetailView, ListView

from .forms import CategoryForm
from .models import Category


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    context_object_name = 'category'
    form_class = CategoryForm


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    context_object_name = 'category'
    form_class = CategoryForm

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        #context['form'].fields['employee'].queryset = Employee.objects.from_group(self.kwargs['group_slug'])
        return context

    def form_valid(self, form):
        #obj = form.save(commit=False)
        #employee = Employee.objects.get(user=self.request.user)
        #obj.coach = employee
        #obj.save()
        return super(CategoryCreateView, self).form_valid(form)


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    context_object_name = 'category'


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    context_object_name = 'categories'

    def get_queryset(self):
        qs = super(CategoryListView, self).get_queryset()
        # Filter qs if need be
        return qs

wild_bills/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


# class WildBillsProfileCreateView(CreateView):
#
#     model = WildBillsProfile
#     context_object_name = 'wbprofile'
#     form_class = WildBillsProfileForm
#     success_url = '/'
#
#     def get_initial(self):
#         ip = get_ip(self.request)
#         logger.debug('Client IP: %s' % ip)
#         country_code = geo_ip_finder.get_country_code(ip)
#         logger.debug('Client country: %s' % country_code)
#         if country_code == 'XX':
#             logger.warn('Had to coerce country to Panama')
#             country_code = 'PA'
#         data = {'country': country_code}
#         return data
#
#
# class WildBillsProfileUpdateView(LoginRequiredMixin, UpdateView):
#     model = WildBillsProfile
#     context_object_name = 'wbprofile'
#     form_class = WildBillsProfileForm
#     success_url = '/'
#
#     def get(self, request, *args, **kwargs):
#         if request.user.pk:
#             if request.user.pk != int(kwargs['pk']):
#                 return HttpResponseForbidden(_('You cannot modify other profiles but your own!!'))
#         return super(WildBillsProfileUpdateView, self).get(request, *args, **kwargs)

wild_bills/templates/bills/bill_list.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 i18n %}
{% block extra_css %}
{{ form.media }}
{% endblock extra_css %}
{% block page_title %}
{% trans 'Bill List' %}
{% endblock page_title %}

{% block content %}
<table class="table">
    <thead>
    <tr class="row">
        <th>
            {% trans 'Action' %}
        </th>
        <th>
            {% trans 'Debt' %}
        </th>
         <th>
            {% trans 'Amount' %}
        </th>
         <th>
            {% trans 'Due Date' %}
        </th>
    </tr>
    </thead>
    <tbody>
    {% for bill in bills %}
    <tr class="row">
        <td class="col-md-1">
            <a  href="{% url 'bills:payment-create' bill.pk %}"
                class="btn btn-primary btn-small" role="button">
               {% trans "Pay" %}
            </a>
        </td>
        <td class="col-md-2" id="payee-{{ bill.pk }}">
            {{ bill.debt.payee }}
        </td>
        <td class="col-md-2" id="amount-due-{{ bill.pk }}">
            {{ bill.amount_due }}
        </td>
    <td class="col-md-2" id="due-date-{{ bill.pk }}">
            {{ bill.due_date }}
        </td>
    </tr>
    {% endfor %}
    </tbody>

</table>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

wild_bills/templates/bills/debt_detail.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 i18n %}
{% block extra_css %}
    {{ form.media }}
{% endblock extra_css %}
{% block page_title %}
    {% trans 'Debt Detail' %}
{% endblock page_title %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            {% trans 'Category' %}
        </div>
        <div class="col-md-6" id="id_category">
            {{ debt.category }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Payee' %}
        </div>
        <div class="col-md-6" id="id_payee">
            {{ debt.payee }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Description' %}
        </div>
        <div class="col-md-6" id="id_description">
            {{ debt.description }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Amount' %}
        </div>
        <div class="col-md-6" id="id_amount">
            {{ debt.amount }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Is Amount Fixed?' %}
        </div>
        <div class="col-md-6">
            {{ debt.fixed_amount }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Organization' %}
        </div>
        <div class="col-md-6">
            {{ debt.organization }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'Frequency' %}
        </div>
        <div class="col-md-6">
            {{ debt.frequency }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% trans 'End Date' %}
        </div>
        <div class="col-md-6">
            {{ debt.end_date }}
        </div>
    </div>
    <div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary" href="{% url 'bills:debt-update' debt.pk %}">
             {% trans 'Edit' %}
        </a>
        <a class="btn btn-primary" href="{% url 'bills:debt-delete' debt.pk %}">
             {% trans 'Delete' %}
        </a>
    </div>
    </div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

wild_bills/templates/bills/debt_form.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extra_css %}
    {{ form.media }}
{% endblock extra_css %}
{% block page_title %}
    {% if debt == None %}
        {% trans 'Add a new debt' %}
    {% else %}
        {% trans 'Editing debt to ' %}{{ debt.payee }}
    {% endif %}

{% endblock page_title %}

{% block content %}
    {% if messages %}
        {% regroup messages|dictsort:"tags" by tags as message_list %}

        {% for tags in message_list %}
            <div class="alert alert-{{ tags.grouper }}">
                <div class="container">
                    <ul>
                        {% for message in tags.list %}
                            <li>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.payee %}
            </div>
            <div class="col-md-4">
                {% bootstrap_field form.amount %}
            </div>
            <div class="col-md-2">
                {% bootstrap_field form.fixed_amount %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.category %}
                </div>
            <div class="col-md-6">
                {% bootstrap_field form.description %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.frequency %}
            </div>
            <div class="col-md-6">
                {% bootstrap_field form.frequency_values %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="id_start_date" class="control-label">{{ form.start_date.label }}</label>
                    <input
                            type="text" value="{{ form.start_date.value|date:'Y-m-d'  }}" title=""
                            placeholder="{{ form.start_date.label }}" name="start_date"
                            id="id_start_date" class="form-control datepicker">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">

                    <label for="{{ form.end_date.id_for_label }}" class="control-label">{{ form.end_date.label }}</label>
                    <input type="text" title="" placeholder="{{ form.end_date.label }}" name="end_date"
                           id="{{ form.end_date.id_for_label }}"
                           value="{{ form.end_date.value|date:'Y-m-d'  }}" class="form-control datepicker">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% bootstrap_field form.organization %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input class="btn btn-primary" role="button" type="submit" name="_save" value="{% trans 'Save' %}">
                <input class="btn btn-primary" role="button" type="submit" name="_add_another"
                       value="{% trans 'Save and add another' %}">
                {% if debt == None %}
                    <a id="cancel-btn" class="btn btn-primary" role="button"
                       href="{% url 'bills:debt-list' %}">{% trans 'Cancel' %}</a>
                {% else %}
                    <a id="cancel-btn" class="btn btn-primary" role="button"
                       href="{% url 'bills:debt-detail' debt.pk %}">{% trans 'Cancel' %}</a>
                {% endif %}
            </div>
        </div>

    </form>
{% endblock content %}

{% block extra_js %}
    <script>
        $.datepicker.setDefaults({
            showOn: "both",
        });
        $.datepicker.setDefaults($.datepicker.regional["{{ LANGUAGE_CODE }}"]);
        $(".datepicker").datepicker({
            dateFormat: "yy-mm-dd",
            altFormat: "yy-mm-dd"
        });
    </script>
{% endblock extra_js %}

wild_bills/templates/bills/paid_bill_list.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 i18n %}
{% block extra_css %}
    {{ form.media }}
{% endblock extra_css %}
{% block page_title %}
    {% trans 'Paid Bills' %}
{% endblock page_title %}

{% block content %}
    <table class="table">
        <thead>
        <tr class="row">

            <th>
                {% trans 'Debt' %}
            </th>
            <th>
                {% trans 'Amount' %}
            </th>
            <th>
                {% trans 'Due Date' %}
            </th>
            <th>
                {% trans 'Payments' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for bill in bills %}
            <tr class="row">
                <td class="col-md-2" id="payee-{{ bill.pk }}">
                    {{ bill.debt.payee }}
                </td>
                <td class="col-md-2" id="amount-due-{{ bill.pk }}">
                    {{ bill.amount_due }}
                </td>
                <td class="col-md-2" id="due-date-{{ bill.pk }}">
                    {{ bill.due_date|date:"d-b-Y" }}
                </td>
                <td class="col-md-2" id="payments-{{ bill.pk }}">
                    {% for payment in bill.payments.all %}
                        <div>
                            {{ payment.amount }}
                        </div>
                        <div>
                            {{ payment.date_paid|date:'d-b-Y' }}
                        </div>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
        {% if is_paginated %}
            <tfoot>
            <tr class="row">
                <td colspan="4">
                    <nav>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li>
                                    <a href="{% url 'bills:bill-list-paid' %}?page={{ page_obj.previous_page_number }}"
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                                <li {% if page_obj.number == i %} class="active" {% endif %}>
                                    <a href="{% url 'bills:bill-list-paid' %}?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="{% url 'bills:bill-list-paid' %}?page={{ page_obj.next_page_number }}"
                                       aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </td>
            </tr>
            </tfoot>

        {% endif %}

    </table>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

wild_bills/templates/bills/payment_form.html
{% extends "base.html" %}
{% load staticfiles bootstrap3 i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extra_css %}
{{ form.media }}
{% endblock extra_css %}
{% block page_title %}
{% trans 'Payment' %}
{% endblock page_title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    {{ form.date_paid.errors }}
                    <label for="{{ form.date_paid.id_for_label }}" class="control-label">{{ form.date_paid.label }}</label>
                    <input
                            type="text" value="{{ form.date_paid.value|date:'Y-m-d'  }}" title=""
                            placeholder="{{ form.date_paid.label }}" name="date_paid"
                            id="{{ form.date_paid.id_for_label }}" class="form-control datepicker">
                </div>
            </div>
            <div class="col-md-6">
                {{ form.amount.errors }}
                {% bootstrap_field form.amount %}
            </div>
        </div>
    <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.reference %}
            </div>
            <div class="col-md-6">
                {% bootstrap_field form.detail %}
            </div>
        </div>
    <div class="row">
        <div class="col-md-6">
        <input class="btn btn-primary" role="button" type="submit" value="{% trans 'Save' %}">
        <a id="cancel-btn" class="btn btn-primary" role="button"
                       href="{% url 'bills:bill-list' %}">{% trans 'Cancel' %}</a>
        </div>
    </div>
    {% bootstrap_field form.bill %}
</form>
{% endblock content %}

{% block extra_js %}
    <script>
        $.datepicker.setDefaults({
            showOn: "both",
        });
        $.datepicker.setDefaults($.datepicker.regional["{{ LANGUAGE_CODE }}"]);
        $(".datepicker").datepicker({
            dateFormat: "yy-mm-dd",
            altFormat: "yy-mm-dd"
        });
    </script>
{% endblock extra_js %}